name: esnap
description: A mobile app for managing your clothes and accesories
version: 1.0.2+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  country_flags: ^2.1.1
  equatable: ^2.0.5
  esnap_api:
    path: packages/esnap_api
  esnap_repository:
    path: packages/esnap_repository
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  formz: ^0.6.0
  image_picker: ^0.8.9
  intl: ^0.18.0
  local_storage_esnap_api:
    path: packages/local_storage_esnap_api
  multi_select_flutter: ^4.1.3
  preferences_api:
    path: packages/preferences_api
  preferences_api_services:
    path: packages/preferences_api_services
  preferences_repository:
    path: packages/preferences_repository
  wid_design_system: ^0.2.6

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/splash.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icon/
    - assets/img/

  fonts:
    - family: Quicksand
      fonts:
        - asset: packages/wid_design_system/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: packages/wid_design_system/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: packages/wid_design_system/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: packages/wid_design_system/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: packages/wid_design_system/fonts/Quicksand-Light.ttf
          weight: 300
