name: preferences_api_services
description: A Flutter implementation of the PreferencesApi using flutter_secure_storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^5.0.1
  preferences_api:
    path: ../preferences_api
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
