name: local_storage_esnap_api
description: A Flutter implementation of the EsnapApi that uses local storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  esnap_api:
    path: ../esnap_api
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
